
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A237E',
    paddingHorizontal: 16,
    paddingTop: 60,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  header: {
    fontFamily: 'PressStart2P',
    fontSize: 20,
    color: '#FFA726',
    textShadowColor: '#FF0044',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 1,
    marginBottom: 16,
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 300,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: '#FFA726',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statLabel: {
    fontFamily: 'PressStart2P',
    fontSize: 8,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  statValue: {
    fontFamily: 'PressStart2P',
    fontSize: 16,
    color: '#4CAF50',
  },
  timeValue: {
    fontFamily: 'PressStart2P',
    fontSize: 12,
    color: '#FFD700',
  },
  quizContainer: {
    flex: 1,
    marginBottom: 20,
  },
  quizContent: {
    paddingBottom: 20,
  },
  emptyState: {
    padding: 40,
    alignItems: 'center',
  },
  emptyStateText: {
    fontFamily: 'PressStart2P',
    fontSize: 12,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  questionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 4,
    borderColor: '#FF9800',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  questionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  questionNumber: {
    fontFamily: 'PressStart2P',
    fontSize: 10,
    color: '#3B0A00',
  },
  pointsBadge: {
    backgroundColor: '#FFA726',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#FF4081',
  },
  pointsText: {
    fontFamily: 'PressStart2P',
    fontSize: 8,
    color: '#3B0A00',
  },
  questionText: {
    fontFamily: 'PressStart2P',
    fontSize: 10,
    color: '#3B0A00',
    marginBottom: 16,
    textAlign: 'center',
    lineHeight: 14,
    flexWrap: 'wrap',
  },
  optionsContainer: {
    width: '100%',
  },
  optionButton: {
    borderRadius: 12,
    padding: 12,
    marginVertical: 6,
    borderWidth: 3,
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  optionContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionLetter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1A237E',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  optionLetterText: {
    fontFamily: 'PressStart2P',
    fontSize: 8,
    color: '#FFFFFF',
  },
  optionText: {
    fontFamily: 'PressStart2P',
    fontSize: 9,
    color: '#3B0A00',
    flex: 1,
    flexWrap: 'wrap',
    lineHeight: 12,
  },
  backButton: {
    backgroundColor: '#FFA726',
    borderColor: '#FF4081',
    borderWidth: 4,
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 12,
    marginBottom: 30,
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    alignSelf: 'center',
    minWidth: 200,
  },
  backButtonText: {
    fontFamily: 'PressStart2P',
    fontSize: 10,
    color: '#3B0A00',
    textAlign: 'center',
  },
});

export { styles };
