export const TOWNS = [
  'Ang Mo Kio',
  'Bishan',
  'Bukit Timah',
  'Orchard',
  'Woodlands',
  'Jurong East',
  'Bukit Merah',
  'Downtown Core',
  'Geylang',
  'Kallang',
  'Marine Parade',
  'Newton',
  'Novena',
  'Outram',
  'Queenstown',
  'River Valley',
  'Rochor',
  'Singapore River',
  'Southern Islands',
  'Tanglin',
  'Toa Payoh',
  'Bedok',
  'Changi',
  'Pasir Ris',
  'Paya Lebar',
  'Tampines',
  'Hougang',
  'Punggol',
  'Seletar',
  'Sengkang',
  'Serangoon',
  'Mandai',
  'Sembawang',
  'Sungei Kadut',
  'Yishun',
  'Bukit Batok',
  'Bukit Panjang',
  'Choa Chu Kang',
  'Clementi',
  'Jurong West',
  'Pioneer',
  'Tengah'
];
